FROM nginx:alpine

# Copy the build files from the previous stage
COPY ./dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]




# docker build -t mcqs_frontend_already_build .
# docker run -p 5173:5173 -d mcqs_frontend_already_build


