# docker-compose_Addedfrontend.yml
version: "3"
services:
  mongo:
    image: mongo:latest
    # volumes:
    #   - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    image: mcqs_backend
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017/MCQsShuffle
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  front_end:
    image: mcqs_frontend
    depends_on:
      - app
    ports:
      - "5173:5173"
# volumes:
#   mongo_data:

